name: build-linter-plugins
on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  build-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Custom Linter
        run: |
          chmod +x scripts/restrictimports.sh
          ./scripts/restrictimports.sh
          chmod +x scripts/gomodcheck.sh
          ./scripts/gomodcheck.sh